begin;
select plan(15);
select has_table('public','reader_profiles','private passport');
select has_table('public','xp_award_metadata','semantic award sources');
select has_table('public','quest_instances','quest history');
select has_table('public','achievement_progress','achievement progress');
select has_table('public','user_cosmetics','collection state');
select is((select relrowsecurity from pg_class where oid='public.reader_profiles'::regclass),true,'profile RLS');
select is((select relrowsecurity from pg_class where oid='public.quest_instances'::regclass),true,'quest RLS');
select is((select relrowsecurity from pg_class where oid='public.achievement_progress'::regclass),true,'achievement RLS');
select is((select relrowsecurity from pg_class where oid='public.user_cosmetics'::regclass),true,'cosmetic RLS');
select ok(not has_table_privilege('anon','public.reader_profiles','SELECT'),'anonymous cannot read passport');
insert into auth.users(id) values('00000000-0000-0000-0000-000000000071');
insert into public.reader_profiles(owner_id,display_name,avatar_symbol,reading_since) values('00000000-0000-0000-0000-000000000071','Reader','person.crop.circle',2020);
insert into public.quest_instances(owner_id,id,template_key,cadence,period_key,title,unit,target,progress) values('00000000-0000-0000-0000-000000000071','00000000-0000-0000-0000-000000000072','pages.genuine','daily','2026-10-06','Turn pages','recorded pages',10,4);
set local role authenticated; select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000071',true);
select is((select count(*)::int from public.reader_profiles),1,'owner reads passport');
select is((select count(*)::int from public.quest_instances),1,'owner reads quests');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000073',true);
select is((select count(*)::int from public.reader_profiles),0,'other owner cannot read passport');
select is((select count(*)::int from public.quest_instances),0,'other owner cannot read quests');
reset role;
select ok(not exists(select 1 from information_schema.tables where table_schema='public' and table_name in ('currency','loot','offers')),'no economy tables');
select * from finish(); rollback;
