begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
select has_table('public','import_runs','Committed import history');
select has_table('public','import_candidates','Normalized review evidence');
select has_table('public','import_occurrences','Stable occurrence identities');
select ok((select relrowsecurity from pg_class where oid='public.import_runs'::regclass),'History RLS');
select ok((select relrowsecurity from pg_class where oid='public.import_candidates'::regclass),'Candidates RLS');
select ok((select relrowsecurity from pg_class where oid='public.import_occurrences'::regclass),'Occurrences RLS');
select ok(not has_table_privilege('anon','public.import_runs','SELECT'),'Anonymous history denied');
select ok(not has_table_privilege('authenticated','public.import_runs','INSERT'),'Raw import write denied');
select ok(not has_table_privilege('authenticated','public.import_candidates','UPDATE'),'Raw resolution denied');
select ok(not has_table_privilege('authenticated','public.import_occurrences','DELETE'),'Raw history deletion denied');
insert into public.import_runs values('00000000-0000-0000-0000-000000000082','80000000-0000-0000-0000-000000000082','fixture',now(),1,0,0,1,0);
select throws_ok($$update public.import_runs set rows_count=0$$,'P0001','Immutable history cannot be modified','History cannot be rewritten');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000081',true);
select is((select count(*)::integer from public.import_runs),0,'Other owner cannot read import history');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000082',true);
select is((select count(*)::integer from public.import_runs),1,'Owner can read import history');
reset role;
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name in ('import_runs','import_occurrences') and column_name in ('journal_format','raw_csv','access_token')),'No external Format/raw CSV/secrets');
select * from finish();
rollback;
