import XCTest
@testable import ReadingDomain

final class Phase7GamificationTests:XCTestCase {
    func testLockedBalanceAndUnlimitedLevels() { XCTAssertEqual(GamificationBalance.amount(for:.finishBook),100); XCTAssertEqual(GamificationBalance.amount(for:.journalWork),40); XCTAssertEqual(GamificationBalance.amount(for:.challengeConfirmation),30); XCTAssertEqual(GamificationBalance.amount(for:.dailyQuest),20); XCTAssertEqual(GamificationBalance.amount(for:.weeklyQuest),60); XCTAssertEqual(GamificationBalance.amount(for:.monthlyQuest),150); XCTAssertEqual(GamificationBalance.level(totalXP:0),1); XCTAssertEqual(GamificationBalance.level(totalXP:5_250),11); XCTAssertEqual(GamificationBalance.progress(totalXP:5_250),250) }
    func testAwardsCannotBeNegativeAndAchievementBoundsAreEnforced() { XCTAssertThrowsError(try XPAward(semanticKey:"bad",source:.finishBook,amount:-1)); XCTAssertThrowsError(try XPAward(semanticKey:"bad",source:.achievement,amount:49)); XCTAssertNoThrow(try XPAward(semanticKey:"level",source:.achievement,amount:0)); XCTAssertNoThrow(try XPAward(semanticKey:"major",source:.achievement,amount:250)) }
    func testQuestCatalogContainsOnlyBehaviorFamiliesAndCorrectVolume() { XCTAssertEqual(Set(QuestCatalog.templates.map(\.family)),Set(QuestFamily.allCases)); let daily=QuestRules.candidates(cadence:.daily,periodKey:"2026-10-06",activity:.init(),history:[]); XCTAssertEqual(daily.count,2); XCTAssertEqual(QuestRules.candidates(cadence:.weekly,periodKey:"2026-W41",activity:.init(),history:[]).count,3); XCTAssertEqual(QuestRules.candidates(cadence:.monthly,periodKey:"2026-10",activity:.init(),history:[]).count,3) }
    func testAdaptiveTargetsAreSmoothedCappedAndNeverUseSyntheticPercentagePages() { let activity=ActivitySummary(genuinePagesPerDay:[10,12,14,5000]); let page=QuestCatalog.templates.first{$0.family == .pages}!; XCTAssertEqual(QuestRules.target(for:page,cadence:.daily,activity:activity),14); XCTAssertLessThanOrEqual(QuestRules.target(for:page,cadence:.monthly,activity:activity),page.maximum); XCTAssertEqual(QuestRules.target(for:page,cadence:.daily,activity:.init()),page.minimum) }
    func testRerolledTemplateIsExcludedFromImmediateReplacement() { let old=QuestInstance(templateKey:"pages.genuine",cadence:.daily,periodKey:"today",title:"Old",unit:"pages",target:10); let next=QuestRules.candidates(cadence:.daily,periodKey:"today",activity:.init(),history:[],excluding:[old.templateKey]); XCTAssertFalse(next.contains{$0.templateKey==old.templateKey}) }
    func testCatalogsHaveNoEconomyOrFeatureLocks() { XCTAssertTrue(CosmeticCatalog.all.allSatisfy{$0.unlockLevel>=1}); XCTAssertTrue(AchievementCatalog.all.allSatisfy{$0.xp==0 || GamificationBalance.achievementRange.contains($0.xp)}); XCTAssertEqual(Set(CosmeticCatalog.all.map(\.category)),Set(CosmeticCategory.allCases)) }
}
